### ISSUE TITLE
does not work for me

### ISSUE THREAD

**Issue by mananhiteshkataria** [mcastorina/mpv-remote-app#32]
Windows 10 user 
powershell showing this error

was running as admin

PS C:\Users\manan> mpv-remote-app password
Traceback (most recent call last):
  File "c:\users\manan\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\manan\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\manan\AppData\Local\Programs\Python\Python37\Scripts\mpv-remote-app.exe\__main__.py", line 9, in <module>
  File "c:\users\manan\appdata\local\programs\python\python37\lib\site-packages\mpv_remote_app\__init__.py", line 85, in main
    set_root(args)
  File "c:\users\manan\appdata\local\programs\python\python37\lib\site-packages\mpv_remote_app\__init__.py", line 49, in set_root
    args.root = abspath(realpath((args.root)))
  File "c:\users\manan\appdata\local\programs\python\python37\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType
PS C:\Users\manan>

**Comment by mcastorina** [comment]
It looks like this is coming from the `HOME` environment not being set here: https://github.com/mcastorina/mpv-remote-app/blob/master/server/mpv_remote_app/__init__.py#L32

A temporary workaround would be to either export a HOME variable or use the `--root` flag:
```
mpv-remote-app password --root 'c:\users\manan'
```

I've actually never tested on Windows so I'm interested to see if there are any other problems. Please open up issues for anything else you may run into. Thanks!

**Comment by mcastorina** [comment]
I just pushed some changes and updated the package on PyPI.

Let me know if that works. If not, I'll have to get a Windows VM to test.

**Comment by mananhiteshkataria** [comment]
Ill do it and reply to you i tried on my elementary os machine the app works fine there but i have noticed the file must be launched locally and i tend to do a lot of dlna stuff but good work :)

**Comment by mananhiteshkataria** [comment]
okay so good and bad news the mpv app opens but its not workable but thats a good start compared to before :)





PS C:\Windows\system32> mpv-remote-app password --root 'c:\users\manan'
Traceback (most recent call last):
  File "C:\Python27\Scripts\mpv-remote-app-script.py", line 11, in <module>
    load_entry_point('mpv-remote-app==0.0.1', 'console_scripts', 'mpv-remote-app')()
  File "c:\python27\lib\site-packages\mpv_remote_app\__init__.py", line 97, in main
    controller=MpvController(args.mpv_socket))
  File "c:\python27\lib\site-packages\mpv_remote_app\media_controllers.py", line 93, in __init__
    super().__init__(unix_socket)
TypeError: super() takes at least 1 argument (0 given)

**Comment by mcastorina** [comment]
Ah yes, the server only works with Python3. I should probably figure out a way to warn and exit cleanly if it is running on Python2.

**Comment by mananhiteshkataria** [comment]
> 
> 
> Ah yes, the server only works with Python3. I should probably figure out a way to warn and exit cleanly if it is running on Python2.

i had p3.8 im guessing some packages got installed with node js

**Comment by mananhiteshkataria** [comment]
yup not getting any wierd glitches now

**Comment by mananhiteshkataria** [comment]
okay so i was loading file from app  and it wont load and cant control

**Comment by mcastorina** [comment]
Okay, thanks for testing that. I think I'll have to debug in a VM.

My initial guess is that there is some unix specific filepath code in the Android app / server that's causing the issues, but we'll see.

**Comment by mcastorina** [comment]
Okay, I was able to capture some debug logs on a Windows VM:

```
INFO:root:Received command: "{'path': './Downloads/out.mp4', 'time': '1576306727714', 'command': 'play'}"
DEBUG:root:send_command: {"command": ["loadfile", "C:\\Users\\Test\\Downloads\\out.mp4"]}
DEBUG:root:Mpv request: "{"command": ["loadfile", "C:\\Users\\Test\\Downloads\\out.mp4"]}"
DEBUG:root:send_command exception: module socket has no attribute AF_UNIX
DEBUG:root:Sending ACK: "{"action": 1576306727714, "time": 1576313926944, "result": false, "message": null}"
```

Two things to note:
- The Android app sends a unix style path to play (though the server was able to interpret it just fine)
- The main problem is that the server is trying to communicate to mpv using an `AF_UNIX` socket which does not exist on Windows

**Comment by mananhiteshkataria** [comment]
i see

**Comment by mananhiteshkataria** [comment]
it is as you predicted

**Comment by mcastorina** [comment]
What would make this easier is support for AF_UNIX sockets in the Windows version of Python. It appears to be planned for Python 3.9 (which will be in the release candidate phase on 2020-08-10). Hopefully I find workaround before then, though.

https://bugs.python.org/issue33408
