### ISSUE TITLE
server dies on long lists

### ISSUE THREAD

**Issue by Bfgeshka** [mcastorina/mpv-remote-app#38]
There's a directory with a couple thousands of files. When entering here via clent, server dies:

```
INFO:root:Received command: "{'time': 1623258978499, 'directory': './curl/ftp_shares/volb/v', 'command': 'list'}"
Traceback (most recent call last):
  File "/home/bfg/.local/bin/mpv-remote-app", line 8, in <module>
    sys.exit(main())
  File "/home/bfg/.local/lib/python3.8/site-packages/mpv_remote_app/__init__.py", line 99, in main
    ms.run(daemon=args.daemon)
  File "/home/bfg/.local/lib/python3.8/site-packages/mpv_remote_app/media_server.py", line 53, in run
    self._serve(self._recv())
  File "/home/bfg/.local/lib/python3.8/site-packages/mpv_remote_app/media_server.py", line 207, in _serve
    if ack: self._ack(ret, msg)
  File "/home/bfg/.local/lib/python3.8/site-packages/mpv_remote_app/media_server.py", line 127, in _ack
    self.sock.sendto(response, self.client)
OSError: [Errno 90] Message too long
```

**Comment by mcastorina** [comment]
Wow! I'm not surprised it dies :laughing: -- there's no pagination support in the server / client yet.

It will take me some time to add this, unfortunately. Contributions are welcome if you (or anyone else) is interested.
